#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BASE_LAUNCHER="${SCRIPT_DIR}/single_gpu/tucker_transformer/fineweb_standard_attention_tensorion_muon_adamw_tucker_retract_1x_chinchilla_wd002.sh"

TUCKER_MODE_LAYOUT=${TUCKER_MODE_LAYOUT:?TUCKER_MODE_LAYOUT is required}
TUCKER_RANK_PLAN=${TUCKER_RANK_PLAN:?TUCKER_RANK_PLAN is required}
case "${TUCKER_MODE_LAYOUT}" in
    order3_input) INITIAL_PARAMETERS=225000704 ;;
    order3_output) INITIAL_PARAMETERS=224997120 ;;
    order3_paired) INITIAL_PARAMETERS=224999552 ;;
    *) echo "Expected order3_input, order3_output, or order3_paired" >&2; exit 2 ;;
esac

export EXPERIMENT_NAME=${EXPERIMENT_NAME:-"llama257m_tucker3_${TUCKER_MODE_LAYOUT}_late_225m_to_257m_customfb_bs16acc8_production_run1"}
export TARGET_PARAMETER_COUNT=${INITIAL_PARAMETERS}
export TARGET_PARAMETER_TOLERANCE=0
export TUCKER_RANK_PLAN
export TUCKER_MODE_LAYOUT
export TUCKER_PROGRESSIVE_STAGES=${TUCKER_PROGRESSIVE_STAGES:-"0:${INITIAL_PARAMETERS} 32325:235025776 33325:244430608 34325:253728016 35325:257676352"}
export TUCKER_PROGRESSIVE_WARMUP_STEPS=${TUCKER_PROGRESSIVE_WARMUP_STEPS:-400}
export TUCKER_PROGRESSIVE_SEED=${TUCKER_PROGRESSIVE_SEED:-1701}
export TUCKER_PROGRESSIVE_VERIFY_RTOL=${TUCKER_PROGRESSIVE_VERIFY_RTOL:-5e-5}

export SINGLE_PROCESS=1
export TRAIN_ENTRY="experiments/fused_persistent_tucker/custom_backward/train_entry.py"
export TUCKER_FORWARD_MODE=chunked_contract
export TUCKER_CUSTOM_CACHE_POLICY=recast
export TUCKER_PARALLEL_MUON=0
export TUCKER_GROUPED_RETRACTION=1
export TUCKER_VECTOR_TRANSPORT=1
export TUCKER_RIEMANNIAN_MUON=1
export TUCKER_DENSE_ADAMW_MATRICES=1
export TUCKER_LR_SCALING_MODE=none
export TUCKER_LR_SCALING_POST_NS_PROJECT=0
export TUCKER_LR_SCALING_USE_STIEFEL_UNIT_NORM=1
export WEIGHT_DECAY=0.1
export WEIGHT_DECAY_TAG=wd01

export ITERATIONS=${ITERATIONS:-39250}
export WARMUP=${WARMUP:-2000}
export BATCH_SIZE=${BATCH_SIZE:-16}
export ACC_STEPS=${ACC_STEPS:-8}
export EVAL_BATCH_SIZE=${EVAL_BATCH_SIZE:-16}
export EVAL_BATCHES=${EVAL_BATCHES:-16}
export SAVE_BEST_VAL_CHECKPOINT=${SAVE_BEST_VAL_CHECKPOINT:-1}
export LATEST_CKPT_INTERVAL=${LATEST_CKPT_INTERVAL:-500}

exec bash "${BASE_LAUNCHER}"
